### ISSUE TITLE
Support negative numbers [enhancement]

### ISSUE THREAD

**Issue by hippyau** [Tyill/interpreter#2]
Hi there,

  I found I can support negative numbers like:

```
-> summ(-1,24-23);
-> OK: 0
-> summ(-1,24-12);
-> OK: 11
-> 
```

 by adding ` if (leftOpd == "") leftOpd = "0";` to the "-" operator, and dot / minus support to isNumber()

```
  bool isNumber(const std::string &s)
    {      
        for (auto c : s)
        {
            if ( (!std::isdigit(c)) && (c != '.') && (c != '-'))
            {
                return false;
            }
        }
        return !s.empty();
    }

        ir->addOperator(
            "-", [](string &leftOpd, string &rightOpd) -> string {
                if (leftOpd == "") leftOpd = "0"; // negative number, such as "-1" so we deduct right from 0
                if (isNumber(leftOpd) && isNumber(rightOpd))
                    return to_string(stoi(leftOpd) - stoi(rightOpd));
                else
                    return "0";
            },
            1);
```

are there any side effects?  

Also I've had some initial success with supporting floats like `1.22`,  is there already support I am missing?

Cheers,
 Hip

**Comment by hippyau** [comment]
Further notes: 

wrong:
```
-> summ(0,12 - -1);
-> OK: -1
```

correct:
```
-> summ(0,12-(-1));
-> OK: 13
```

**Comment by Tyill** [comment]
Hi.  
There are no types as such, only strings. You must implement the conversion from the string yourself if you want to work with numbers.

**Comment by hippyau** [comment]
Hi, this simple kludge above implements negative numbers, is working well.
