### ISSUE TITLE
Operator awareness of parent function?

### ISSUE THREAD

**Issue by hippyau** [Tyill/interpreter#3]
Is there a mechanism or suggestion how that that the operator can know it's parent function?

eg:  `lettuce(1->24);`  

```
        ir->addOperator( // a selection
            "->", [](string &leftOpd, string &rightOpd) -> string {
                
                if (isNumber(leftOpd) && isNumber(rightOpd)){
                    uint a = stoi(leftOpd);
                    uint b = stoi(rightOpd);
                    for (int cnt = a; cnt <= b; cnt++){
                        printf("select %s %d \n\r", ___parent_function_name___, cnt);
                    }
                }
                return ""; // return nothing - ignore?
            },
            0);
```

would output...

```
select lettuce 1
select lettuce 2
select lettuce 3
...
select lettuce 22
select lettuce 23
select lettuce 24
```

**Comment by Tyill** [comment]
No, there is no such thing.

**Comment by Tyill** [comment]
I'll think about how to do it.

**Comment by hippyau** [comment]
okay cool,  thanks :+1: 

I now wonder how I might go about implementing.

**Comment by Tyill** [comment]
Added reflection, see [example](https://github.com/Tyill/interpreter/blob/main/src/test.cpp#L206), and [functions](https://github.com/Tyill/interpreter/blob/main/include/interpreter.h#L98).

https://github.com/Tyill/interpreter/releases/tag/1.0.6

**Comment by Tyill** [comment]
How to get the function name:

```cpp
ir.addFunction("lettuce", [&ir](const vector<string>& args) ->string {
      return !args.empty() ? args[0] : "";
  });

ir.addOperator( // a selection
    "->", [&ir](string &leftOpd, string &rightOpd) -> string {

    auto entities = ir.allEntities();

    auto curEntity = ir.currentEntity();

    int index = curEntity.beginIndex - 1;
    while ((index >= 0) && (entities[index].type != Interpreter::EntityType::FUNCTION))
        --index;

    string parentFunctionName = "";
    if (index >= 0)
        parentFunctionName = entities[index].name;

    if (isNumber(leftOpd) && isNumber(rightOpd)) {
        int a = stoi(leftOpd);
        int b = stoi(rightOpd);
        for (int cnt = a; cnt <= b; cnt++) {
            printf("select %s %d \n\r", parentFunctionName.c_str(), cnt);
        }
    }
    return parentFunctionName;
}, 0);

string scenar = "lettuce(1->24);";

string res = ir.cmd(scenar); // lettuce

```

**Comment by hippyau** [comment]
Hi Tyill!  Thanks so much,  this works, but breaks the multiple instances #1 when using a vector.

This had me stumped, but I think it's because `Interpreter *pIr = &ir;` is invalidated when `its.push_back(test2);` is used and the object is moved...  ~~Any way around this while still being able to use a dynamic array?~~

Solved:  I should be using a deque instead of a vector, and emplace_back() instead to create the objects in place, instead of using push_back() and moving an object there. facepalm.
